services:
  postgres:
    image: postgres
    container_name: ${DB_CONT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}