
// AI genererad
export interface Language { id: number, name: string, country: string | string[] }
export const languages: Language[] = [
    { id: 1, name: "English/English", country: ["United Kingdom", "United States"] },
    { id: 2, name: "Arabic/العربية", country: "Saudi Arabia" },
    { id: 3, name: "Bengali/বাংলা", country: "Bangladesh" },
    { id: 4, name: "Chinese/中文", country: "China" },
    { id: 5, name: "Croatian/Hrvatski", country: "Croatia" },
    { id: 6, name: "Czech/Čeština", country: "Czech Republic" },
    { id: 7, name: "Danish/Dansk", country: "Denmark" },
    { id: 8, name: "Dutch/Nederlands", country: "Netherlands" },
    { id: 9, name: "Finnish/Suomi", country: "Finland" },
    { id: 10, name: "French/Français", country: "France" },
    { id: 11, name: "German/Deutsch", country: "Germany" },
    { id: 12, name: "Greek/Ελληνικά", country: "Greece" },
    { id: 13, name: "Hebrew/עברית", country: "Israel" },
    { id: 14, name: "Hindi/हिन्दी", country: "India" },
    { id: 15, name: "Hungarian/Magyar", country: "Hungary" },
    { id: 16, name: "Italian/Italiano", country: "Italy" },
    { id: 17, name: "Japanese/日本語", country: "Japan" },
    { id: 18, name: "Korean/한국어", country: "South Korea" },
    { id: 19, name: "Malay/Melayu", country: "Malaysia" },
    { id: 20, name: "Norwegian/Norsk", country: "Norway" },
    { id: 21, name: "Persian/فارسی", country: "Iran" },
    { id: 22, name: "Polish/Polski", country: "Poland" },
    { id: 23, name: "Portuguese/Português", country: ["Portugal", "Brazil"] },
    { id: 24, name: "Romanian/Română", country: "Romania" },
    { id: 25, name: "Russian/Русский", country: "Russia" },
    { id: 26, name: "Serbian/Српски", country: "Serbia" },
    { id: 27, name: "Slovak/Slovenčina", country: "Slovakia" },
    { id: 28, name: "Spanish/Español", country: ["Spain", "Mexico", "Argentina"] },
    { id: 29, name: "Swahili/Kiswahili", country: "Tanzania" },
    { id: 30, name: "Swedish/Svenska", country: "Sweden" },
    { id: 31, name: "Telugu/తెలుగు", country: "India" },
    { id: 32, name: "Thai/ไทย", country: "Thailand" },
    { id: 33, name: "Turkish/Türkçe", country: "Turkey" },
    { id: 34, name: "Ukrainian/Українська", country: "Ukraine" },
    { id: 35, name: "Vietnamese/Tiếng Việt", country: "Vietnam" },
    { id: 36, name: "Zulu/isiZulu", country: "South Africa" }
] as const;